### ISSUE TITLE
Evaluate usage of <b> vs. <strong>, and <i> vs. <em>

### ISSUE THREAD

**Issue by xhamyd** [xhamyd/public_html#29]
`<strong>` should be used for syntactic emphasis, whereas `<b>` should be used only to increase font weight of an element.
`<em>` should be used for syntactic emphases, whereas `<i>` should be used for presentational differentiation.

Reference: <https://www.silkstream.net/blog/2016/02/b-vs-strong-i-vs-em-whats-the-difference.html>

**Comment by Deepakmukka1** [comment]
@xhamyd what should be done to the code?

**Comment by varuns1007** [comment]
I would like to work on this .

**Comment by xhamyd** [comment]
Hi @Deepakmukka1 , thanks for showing interest in my Personal Website project! Right now, I have the project set up for public viewing of my personal contributions to this repo. I have not detailed what needs to be changed in the code, since this ticket is just a quick reminder for me. At this moment, I am not accepting outside contributions to this project.

Since I don't have a contribution license set up for this project, I encourage you to comment on #33 for any bugs or suggestions you may have for the project. Thanks again for your interest, and take care!
