### ISSUE TITLE
Move projects.html to projects/index.html

### ISSUE THREAD

**Issue by xhamyd** [xhamyd/public_html#31]

**Comment by Ujjwal3009** [comment]
Can i try?

**Comment by xhamyd** [comment]
Hi @Ujjwal3009, thanks for showing interest in my Personal Website project! Right now, I have the project set up for public viewing of my personal contributions to this repo. Since I don't have a contribution license set up for this project, I encourage you to comment on #33 for any bugs or suggestions you may have for the project. Thanks again for your interest, and take care!
